# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  issues :
    types : [labeled]
jobs:
  automate-project-columns:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          project: First Project
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
