# This is a basic workflow to help you get started with Actions

name: Move issue into Waiting

# Controls when the action will run. 
on:
  issues :
    types : [labeled]
jobs:
  automate-project-columns:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: First Project
          column: In progress
          repo-token: ${{ secrets.ACCESS_TOKEN }}
